using AutoMapper;
using ProductManagement.Api.Models;
using ProductManagement.Api.DTOs;

namespace ProductManagement.Api.Utilities.Helper.AutoMapper;
public class CategoryProfile : Profile
{
    public CategoryProfile()
    {
        // 1. Basic Two-Way Mapping
        // ReverseMap() automatically configures the Model -> DTO reverse direction
        CreateMap<Category, CategoryDto>().ReverseMap();

        // 2. Explicit Mapping with Custom Logic
        CreateMap<Category, CategoryRequestDto>().ReverseMap()
            .ForMember(dest => dest.Id, opt => opt.Ignore()); // Id is generated by the database
    }
}